### PR TITLE
done

### PR DESCRIPTION
**Pull request by IBTechRaj**

### CODE REVIEW

**Comment by IBTechRaj** [comment]
Hi, kindly review the code and give your suggestions. thanks

**Comment by dipto0321** [comment]
# Good Job 👏 

Hi @IBTechRaj ,

Congratulations! Code is fine. Okay, In this project the main purpose is to make your own enumerable methods. So, according to this, you can't use built-in `each` method. Here are my suggestions :
- Avoid `each` for `my_each` and `my_each_with_index`. You should use the `for` loop or `while` loop in [here ](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L3), [here](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L3). I know that if you use `rubocop` it will not allow you to use `for` loop. But it's okay for this assignment. So don't worry ⛄️ 

- After finishing your `my_each` method you should use your own `my_each` where you used `each` like in [here ](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L18), [here](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L56), [here](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L75).
- [Here ](https://github.com/IBTechRaj/Enumerables/blob/ef44d1ba66698655c5392e2c1a13250a2b6d1db5/enumerables.rb#L6) is an indentation problem.

After fixing all those things recheck your method with the original method. Then send another request to re-review this code with the same PR link. Please don't merge or close this PR until you get final feedback. If you have any question regarding this feedback or need any clarification just ask me on slack without any hesitation. “I will be happy for helping.

Thanks 🙏

**Comment by IBTechRaj** [comment]
After I ran rubocop, my my_each's have been changed to 'each's.  I corrected them and submitted. Pl review. thanks.

**Comment by dipto0321** [comment]
Hi @IBTechRaj ,
Good job. All methods are working perfectly. I think you accomplished the project main goal. Just one think about your `my_each_with_index`. You can do the same thing this alternative way:
```
def my_each_with_index
    for i in (0...self.size)
      yield self[i], i
    end
  end
```
Now you might ask me. why? the answer is in your code you have to create `i=0` then inside loop, you need to increment `i+=1`. which eat unnecessary space and time while doing the method's job.

This is from me 👍 .  You can merge it into the master. Best of luck! 😄 

Thanks 😌

**Comment by IBTechRaj** [comment]
Thank you very much Dipto for the suggestion. I shall correct it accordingly.

-Raj 

On Thu, 18 Apr 2019 16:21:25 +0530 Dipto Karmakar  wrote
>Hi @IBTechRaj ,

Good job. All methods are working perfectly. I think you accomplished the project main goal. Just one 
think about your my_each_with_index. You can do the same thing this alternative way:
def my_each_with_index
    for i in (0...self.size)
      yield self[i], i
    end
  end

Now you might ask me. why? the answer is in your code you have to create i=0 then inside loop, you need 
to increment i+=1. which eat unnecessary space and time while doing the method's job.
This is from me 👍 .  You can merge it into the master. Best of luck! 😄
Thanks 😌

**Comment by dipto0321** [comment]
Hi @IBTechRaj 

Awesome! Please, Don't send any request to review this code again. I already checked this suggestion with your code and it's work. Just after adding this solution merge it into the master 😺 . But if you face any problem just knock me directly in slack.

Thanks

**Comment by IBTechRaj** [comment]
code review finished and necessary corrections done

**Pull request merged**
